version: '3.7'
services:
  db:
    container_name: upload-files-db
    image: postgres:10-alpine
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
